### ISSUE TITLE
json rpc call parameters formalism across implementations

### ISSUE THREAD

**Issue by patkap** [gciotta/jsonrpc-requests#9]
As per the specs:
>If present, parameters for the rpc call MUST be provided as a Structured value. Either by-position through an Array or by-name through an Object.

Currently, the `params` is always dumped to a json array in `Server.serialize()` method because this [`args`](https://github.com/gciotta/jsonrpc-requests/blob/master/jsonrpc_requests/jsonrpc.py#L88) variable containing the positional arguments is a `tuple`.

I made the following alteration to be able to send "play URI" command to my Kodi system, which seems to accept only a "by-name through an Object" parameter for this peculiar jsonrpc call:

```python
        if params:
            if (isinstance(params, tuple) and
                    isinstance(params[0], dict) and len(params) == 1):
                data['params'] = params[0]
            else:
                data['params'] = params
```

```python
self._server.Player.Open({"item": {"file": str(media_id)}})
```

**Comment by gciotta** [comment]
Hi @patkap,

have you tried calling your function with the `**` operator? Would that work for you? 

`self._server.Player.Open(**{"item": {"file": str(media_id)}})`

Best,
Giuseppe

**Comment by gciotta** [comment]
@patkap, I ended up implementing your suggestion in 52b3cb9 It is now possible to pass top-level mapping types in function calls.
